# 넘파이 Numpy

## numpy as np

In [2]:
# numpy 
import numpy as np
data1 = [1,2,3,4,5]
data2 = [1,2,3,4,5,6]

In [5]:
arr1 = np.array(data1)
arr2 = np.array(data2)
arr1, arr2

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]))

In [10]:
arr1.shape , arr1.dtype

((5,), dtype('int64'))

In [ ]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr3.shape , arr3.dtype

((2, 3), dtype('int64'))

In [20]:
zz = np.zeros(10)
zz, zz.shape , zz.dtype

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), (10,), dtype('float64'))

In [23]:
zzz = np.zeros([3,5])
zzz , zzz.shape , zzz.dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 (3, 5),
 dtype('float64'))

In [24]:
oo = np.ones(7)
oo , oo.shape , oo.dtype

(array([1., 1., 1., 1., 1., 1., 1.]), (7,), dtype('float64'))

In [25]:
ooo = np.ones([2,10])
ooo , ooo.shape , ooo.dtype

(array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 (2, 10),
 dtype('float64'))

In [27]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

## np.array 연산

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])
arr1 , arr2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [30]:
print(arr1.shape , arr1.dtype)
print(arr2.shape , arr2.dtype)

(2, 3) int64
(2, 3) int64


In [43]:
result0 = arr1*3
result1 = arr1 + arr2
result2 = arr1 - arr2
result3 = arr1*2 - arr2/10
result4 = arr1 * arr2
result5 = arr1 / arr2

print(result0)
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)

# 브로드캐스트 : 같은 크기의 배열을 가지지 않아도 요소별 연산이 가능함
arr3 = np.array([22,33,44])
print(arr1 + arr3)
print(arr1 * arr3)


[[ 3  6  9]
 [12 15 18]]
[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[ 1.   2.9  4.8]
 [ 6.7  8.6 10.5]]
[[10 22 36]
 [52 70 90]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]
[[23 35 47]
 [26 38 50]]
[[ 22  66 132]
 [ 88 165 264]]


## 1차원

In [45]:
# 1차원과 속성들
# shape : 배열의 차원정보
# dtype : 배열 원소의 자료형
# size : 배열의 원소 총 개수
# ndim : 축의 개수

arr = np.arange(5)
arr, arr.shape , arr.dtype , arr.size , arr.ndim


(array([0, 1, 2, 3, 4]), (5,), dtype('int64'), 5, 1)

In [46]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,'a','b'])
arr3 = np.array([1,2,3,4], dtype='str')

print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [60]:
arr4 = np.full((4,3),8)                                             # 4x3 행렬을 8로 채움
arr4_1 = np.full((4,3),"없어")                                      # 4x3 행렬을 "없어"로 채움
arr5 = np.eye(3)                                                    # 3x3 단위행렬 생성 (float형)
arr6 = np.linspace(0,100,5, endpoint = False, dtype="int64")        # 칸을 균등하게 분배(arange랑 비슷), float형 int로 변환 가능
arr7 = np.arange(0,100,20)                                          # linspace에 endpoint = False를 안치면 100도 포함
arr4 , arr4_1 , arr5 , arr6 , arr7


(array([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]]),
 array([['없어', '없어', '없어'],
        ['없어', '없어', '없어'],
        ['없어', '없어', '없어'],
        ['없어', '없어', '없어']], dtype='<U2'),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([ 0, 20, 40, 60, 80]),
 array([ 0, 20, 40, 60, 80]))

## 2차원

In [66]:
arr20 = np.array([[1,2],[3,4]])
arr20 , arr20.shape , arr20.size , arr20.dtype , arr20.ndim , type(arr20)

(array([[1, 2],
        [3, 4]]),
 (2, 2),
 4,
 dtype('int64'),
 2,
 numpy.ndarray)

In [77]:
try:
    arr21 = np.arange(1,10).reshape(3,3)
    print(arr21 , arr21.shape , arr21.size , arr21.dtype , arr21.ndim , type(arr21))
    arr22 = np.arange(1,11).reshape(2,5)
    print(arr22 , arr22.shape , arr22.size , arr22.dtype , arr22.ndim , type(arr22))
    arr23 = np.arange(1,19).reshape(3,6)
    print(arr23 , arr23.shape , arr23.size , arr23.dtype , arr23.ndim , type(arr23))
except ValueError as e:
    print("차원과 사이즈가 맞지 않아요")

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 9 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5) 10 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]] (3, 6) 18 int64 2 <class 'numpy.ndarray'>
