# 넘파이 Numpy

## numpy as np

In [2]:
# numpy 
import numpy as np
data1 = [1,2,3,4,5]
data2 = [1,2,3,4,5,6]

In [5]:
arr1 = np.array(data1)
arr2 = np.array(data2)
arr1, arr2

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]))

In [10]:
arr1.shape , arr1.dtype

((5,), dtype('int64'))

In [ ]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr3.shape , arr3.dtype

((2, 3), dtype('int64'))

In [20]:
zz = np.zeros(10)
zz, zz.shape , zz.dtype

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), (10,), dtype('float64'))

In [23]:
zzz = np.zeros([3,5])
zzz , zzz.shape , zzz.dtype

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 (3, 5),
 dtype('float64'))

In [24]:
oo = np.ones(7)
oo , oo.shape , oo.dtype

(array([1., 1., 1., 1., 1., 1., 1.]), (7,), dtype('float64'))

In [25]:
ooo = np.ones([2,10])
ooo , ooo.shape , ooo.dtype

(array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 (2, 10),
 dtype('float64'))

In [27]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

## np.array 연산

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])
arr1 , arr2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 11, 12],
        [13, 14, 15]]))

In [30]:
print(arr1.shape , arr1.dtype)
print(arr2.shape , arr2.dtype)

(2, 3) int64
(2, 3) int64


In [43]:
result0 = arr1*3
result1 = arr1 + arr2
result2 = arr1 - arr2
result3 = arr1*2 - arr2/10
result4 = arr1 * arr2
result5 = arr1 / arr2

print(result0)
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)

# 브로드캐스트 : 같은 크기의 배열을 가지지 않아도 요소별 연산이 가능함
arr3 = np.array([22,33,44])
print(arr1 + arr3)
print(arr1 * arr3)


[[ 3  6  9]
 [12 15 18]]
[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[ 1.   2.9  4.8]
 [ 6.7  8.6 10.5]]
[[10 22 36]
 [52 70 90]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]
[[23 35 47]
 [26 38 50]]
[[ 22  66 132]
 [ 88 165 264]]


## 1차원

In [45]:
# 1차원과 속성들
# shape : 배열의 차원정보
# dtype : 배열 원소의 자료형
# size : 배열의 원소 총 개수
# ndim : 축의 개수

arr = np.arange(5)
arr, arr.shape , arr.dtype , arr.size , arr.ndim


(array([0, 1, 2, 3, 4]), (5,), dtype('int64'), 5, 1)

In [46]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,'a','b'])
arr3 = np.array([1,2,3,4], dtype='str')

print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [60]:
arr4 = np.full((4,3),8)                                             # 4x3 행렬을 8로 채움
arr4_1 = np.full((4,3),"없어")                                      # 4x3 행렬을 "없어"로 채움
arr5 = np.eye(3)                                                    # 3x3 단위행렬 생성 (float형)
arr6 = np.linspace(0,100,5, endpoint = False, dtype="int64")        # 칸을 균등하게 분배(arange랑 비슷), float형 int로 변환 가능
arr7 = np.arange(0,100,20)                                          # linspace에 endpoint = False를 안치면 100도 포함
arr4 , arr4_1 , arr5 , arr6 , arr7


(array([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]]),
 array([['없어', '없어', '없어'],
        ['없어', '없어', '없어'],
        ['없어', '없어', '없어'],
        ['없어', '없어', '없어']], dtype='<U2'),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([ 0, 20, 40, 60, 80]),
 array([ 0, 20, 40, 60, 80]))

## 2차원

In [66]:
arr20 = np.array([[1,2],[3,4]])
arr20 , arr20.shape , arr20.size , arr20.dtype , arr20.ndim , type(arr20)

(array([[1, 2],
        [3, 4]]),
 (2, 2),
 4,
 dtype('int64'),
 2,
 numpy.ndarray)

In [77]:
try:
    arr21 = np.arange(1,10).reshape(3,3)
    print(arr21 , arr21.shape , arr21.size , arr21.dtype , arr21.ndim , type(arr21))
    arr22 = np.arange(1,11).reshape(2,5)
    print(arr22 , arr22.shape , arr22.size , arr22.dtype , arr22.ndim , type(arr22))
    arr23 = np.arange(1,19).reshape(3,6)
    print(arr23 , arr23.shape , arr23.size , arr23.dtype , arr23.ndim , type(arr23))
except ValueError as e:
    print("차원과 사이즈가 맞지 않아요")

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 9 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5) 10 int64 2 <class 'numpy.ndarray'>
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]] (3, 6) 18 int64 2 <class 'numpy.ndarray'>


## 인덱싱(마스크)

In [47]:
import numpy as np
# 난수 발생
# np.random.rand : 균등 분포 , 0~1 사이, 확률 / 비율 등 기본 난수 생성
# np.random.randn : 표준 정규 분포 , 
ran_data = np.random.randn(8,4)
ran_data

array([[ 0.13861272, -0.08310697,  0.83562043,  0.23330766],
       [-1.44431797,  0.77868985, -0.52754434, -0.45732824],
       [-0.78852782, -0.76854173, -0.5710151 ,  0.85815107],
       [ 0.33083264, -0.03424585, -0.73644999,  0.59850887],
       [-1.4507645 , -0.5178343 , -0.11971234,  0.84110986],
       [-1.12977396, -1.12719835, -0.24546784, -0.31083739],
       [ 2.00713691,  0.10194053, -0.09099171,  0.26911043],
       [-0.84493822, -1.60648841, -0.3545138 ,  0.27920113]])

In [ ]:
mask = np.array([True,False,True,False,False,True,True,False])
mask

array([ True, False,  True, False, False,  True,  True, False])

In [7]:
ran_data[mask]

array([[-1.72661609,  0.70198116,  1.07901906,  0.51923743],
       [ 1.10373653, -0.62329781, -0.79738438,  0.88905436],
       [-0.0267716 , -0.732358  ,  1.82722271, -0.25146472],
       [ 0.63058916, -1.03939289,  0.60533603,  0.0814014 ]])

In [ ]:
fruit = np.array(['apple','banana','apple','kiwi','orange','apple','apple','melon'])
fruit

array(['apple', 'banana', 'apple', 'kiwi', 'orange', 'apple', 'apple',
       'melon'], dtype='<U6')

In [10]:
fruit_mask = (fruit == 'apple')
fruit_mask

array([ True, False,  True, False, False,  True,  True, False])

In [11]:
ran_data[fruit_mask]

array([[-1.72661609,  0.70198116,  1.07901906,  0.51923743],
       [ 1.10373653, -0.62329781, -0.79738438,  0.88905436],
       [-0.0267716 , -0.732358  ,  1.82722271, -0.25146472],
       [ 0.63058916, -1.03939289,  0.60533603,  0.0814014 ]])

In [ ]:
ran_data[(fruit == 'apple')|(fruit=='orange'),1:3]      # ran_data[행,열]

array([[ 0.70198116,  1.07901906],
       [-0.62329781, -0.79738438],
       [ 0.01325079,  0.62021113],
       [-0.732358  ,  1.82722271],
       [-1.03939289,  0.60533603]])

## 인덱스와 마스크의 응용

In [17]:
ran_data

array([[-1.72661609,  0.70198116,  1.07901906,  0.51923743],
       [ 0.25216545, -0.60167925, -0.75321461,  0.13210873],
       [ 1.10373653, -0.62329781, -0.79738438,  0.88905436],
       [ 0.84311875,  0.45589479, -0.18016096, -0.46279047],
       [-0.61312255,  0.01325079,  0.62021113, -0.50154526],
       [-0.0267716 , -0.732358  ,  1.82722271, -0.25146472],
       [ 0.63058916, -1.03939289,  0.60533603,  0.0814014 ],
       [-0.43699112,  0.23146432, -1.32922028, -0.84056068]])

In [45]:
ran_data[:,:] > 0

TypeError: 'int' object is not subscriptable

In [51]:
# ran_data에서 0번째 열의 값이 0보다 작은 행의 2,3번째 열의 값만 추출하라.
# 위 값들만 0으로 담아서 전체 배열에다가 표시하라.

row = ran_data[:,0] < 0
result1 = ran_data[row, 2:4]
print(result1)
ran_data[row, 2:4] = 0
print(ran_data)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[ 0.13861272 -0.08310697  0.83562043  0.23330766]
 [-1.44431797  0.77868985  0.          0.        ]
 [-0.78852782 -0.76854173  0.          0.        ]
 [ 0.33083264 -0.03424585 -0.73644999  0.59850887]
 [-1.4507645  -0.5178343   0.          0.        ]
 [-1.12977396 -1.12719835  0.          0.        ]
 [ 2.00713691  0.10194053 -0.09099171  0.26911043]
 [-0.84493822 -1.60648841  0.          0.        ]]


In [ ]:
# np.nan : 숫자타입인데 숫자로 표현할 수 없는 것을 nan으로 표현(결측치)
row = ran_data[:,0] < 0
ran_data[row, 2:4] = np.nan
ran_data

array([[ 0.13861272, -0.08310697,  0.83562043,  0.23330766],
       [-1.44431797,  0.77868985,         nan,         nan],
       [-0.78852782, -0.76854173,         nan,         nan],
       [ 0.33083264, -0.03424585, -0.73644999,  0.59850887],
       [-1.4507645 , -0.5178343 ,         nan,         nan],
       [-1.12977396, -1.12719835,         nan,         nan],
       [ 2.00713691,  0.10194053, -0.09099171,  0.26911043],
       [-0.84493822, -1.60648841,         nan,         nan]])

In [63]:
# any(axis = k)   -- k가 0이면 열 1이면 행
# ~는 반대(not 연산자), nan이 없는 행만 추출하는 것
# ran_data[np.isnan(ran_data).any(axis=1)]
ran_data[~np.isnan(ran_data).any(axis=1)]

array([[ 0.13861272, -0.08310697,  0.83562043,  0.23330766],
       [ 0.33083264, -0.03424585, -0.73644999,  0.59850887],
       [ 2.00713691,  0.10194053, -0.09099171,  0.26911043]])

In [77]:
# fix_data 안에 있는 값 중 -만 제거
# sqrt를 통해 제곱하기

fix_data = ran_data[~np.isnan(ran_data).any(axis=1)]
fix_data2 = np.abs(fix_data)
fix_data3 = np.sqrt(fix_data2)
fix_data3

array([[0.3723073 , 0.28828279, 0.91412277, 0.48301932],
       [0.57518053, 0.18505635, 0.85816665, 0.77363355],
       [1.41673459, 0.31928127, 0.30164832, 0.51875855]])

In [ ]:
# np.log를 통해 로그 데이터 연산
fix_data4 = np.log(fix_data3)
fix_data4

array([[-0.9880357 , -1.24381338, -0.0897904 , -0.72769863],
       [-0.55307133, -1.6870949 , -0.15295697, -0.25665697],
       [ 0.34835464, -1.14168285, -1.19849345, -0.65631673]])

In [ ]:
# np.sign() : -는 -1, +는 1로 표시

np.sign(fix_data4)

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [ 1., -1., -1., -1.]])

In [ ]:
# 삼각함수 값을 계산하기 (cos, cosh, sin, sinh, tan, tanh)

np.cos(fix_data4)

array([[ 0.55033101,  0.3211873 ,  0.99597155,  0.74670714],
       [ 0.85091516, -0.11603658,  0.98832487,  0.967244  ],
       [ 0.93993563,  0.41606482,  0.3637615 ,  0.79224514]])

In [82]:
# 두개의 array에 동일한 위치의 요소끼리 비교 하기

data1 = np.random.randn(8,4)
data2 = np.random.randn(8,4)
data1, data2

(array([[-0.41314491,  0.81166586, -1.4415638 ,  0.83641997],
        [ 1.2534272 , -0.85653589, -0.93079385, -2.75853615],
        [-1.20945005,  0.74116984,  1.13230506, -1.00314601],
        [ 0.80667135, -0.32077595,  0.05418833, -0.34359516],
        [-0.1219559 ,  0.27409738, -0.43013556,  1.38798859],
        [-1.62577422,  0.11739891,  0.0665389 ,  2.16138095],
        [-0.90030896, -0.25396369,  0.01607942, -0.78448035],
        [-0.79002757,  0.65832508, -0.70377048, -0.82329692]]),
 array([[ 0.91374502,  1.59053934, -1.78351664, -1.50782756],
        [ 0.57087724,  0.22283179,  1.49579577,  0.31725379],
        [-1.82657593,  0.32880245, -0.26100508,  1.27050058],
        [-0.40539304,  0.43365139,  1.11165786, -0.85957857],
        [ 0.31399415, -0.12944907,  0.34902163, -1.66710152],
        [ 1.12482737,  0.95524627, -0.20037203, -0.4782921 ],
        [-1.56779971, -1.85953318,  0.60086386, -0.79918024],
        [-1.06850947, -1.21827427, -0.60959097,  0.5808164 ]]))

In [ ]:
# np.maximum : 각 위치의 요소끼리 비교해서 큰값을 뽑는것

np.maximum(data1, data2)

array([[ 0.91374502,  1.59053934, -1.4415638 ,  0.83641997],
       [ 1.2534272 ,  0.22283179,  1.49579577,  0.31725379],
       [-1.20945005,  0.74116984,  1.13230506,  1.27050058],
       [ 0.80667135,  0.43365139,  1.11165786, -0.34359516],
       [ 0.31399415,  0.27409738,  0.34902163,  1.38798859],
       [ 1.12482737,  0.95524627,  0.0665389 ,  2.16138095],
       [-0.90030896, -0.25396369,  0.60086386, -0.78448035],
       [-0.79002757,  0.65832508, -0.60959097,  0.5808164 ]])

In [84]:
# np.minimum : 각 위치의 요소끼리 비교해서 작은값을 뽑는것

np.minimum(data1, data2)

array([[-0.41314491,  0.81166586, -1.78351664, -1.50782756],
       [ 0.57087724, -0.85653589, -0.93079385, -2.75853615],
       [-1.82657593,  0.32880245, -0.26100508, -1.00314601],
       [-0.40539304, -0.32077595,  0.05418833, -0.85957857],
       [-0.1219559 , -0.12944907, -0.43013556, -1.66710152],
       [-1.62577422,  0.11739891, -0.20037203, -0.4782921 ],
       [-1.56779971, -1.85953318,  0.01607942, -0.79918024],
       [-1.06850947, -1.21827427, -0.70377048, -0.82329692]])

In [ ]:
np.maximum(data1, 0) # ReLU(x) 같다.

array([[0.        , 0.81166586, 0.        , 0.83641997],
       [1.2534272 , 0.        , 0.        , 0.        ],
       [0.        , 0.74116984, 1.13230506, 0.        ],
       [0.80667135, 0.        , 0.05418833, 0.        ],
       [0.        , 0.27409738, 0.        , 1.38798859],
       [0.        , 0.11739891, 0.0665389 , 2.16138095],
       [0.        , 0.        , 0.01607942, 0.        ],
       [0.        , 0.65832508, 0.        , 0.        ]])

In [86]:
# 상한 하한 걸기

np.minimum(np.maximum(data2,0.5),1.7)

array([[0.91374502, 1.59053934, 0.5       , 0.5       ],
       [0.57087724, 0.5       , 1.49579577, 0.5       ],
       [0.5       , 0.5       , 0.5       , 1.27050058],
       [0.5       , 0.5       , 1.11165786, 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       ],
       [1.12482737, 0.95524627, 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.60086386, 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5808164 ]])

## 통계함수

In [87]:
data = np.random.randn(4,4)
data

array([[-0.97576085, -1.45253552,  0.61615737,  0.00404219],
       [-0.03530846, -0.08982726, -0.20662687, -0.53902612],
       [-0.26779819,  0.15429606, -0.19863557,  1.05232899],
       [-0.20533911,  0.32118675, -1.41424274, -1.54667553]])

In [88]:
np.sum(data)

np.float64(-4.783764866752382)

In [89]:
np.sum(data, axis=1)

array([-1.80809681, -0.8707887 ,  0.74019128, -2.84507063])

In [90]:
np.sum(data, axis=0)

array([-1.48420661, -1.06687998, -1.20334781, -1.02933047])

In [ ]:
# 0 - 3열 값을 버리고 1-2열의 각 행의 합을 나타내기

np.sum(data[:,1:3], axis=1)

array([-0.83637815, -0.29645413, -0.04433951, -1.09305599])

In [95]:
data2 = np.random.randn(3,5)
data2

array([[-0.07813446, -0.33260748, -0.02619717, -0.66836866, -0.95100545],
       [-0.59535313, -0.96851708,  0.38029659,  0.52801272, -1.28156928],
       [ 1.05973698,  1.41169473,  0.42011507,  1.32492625, -0.62897991]])

In [96]:
np.mean(data2)

np.float64(-0.02706335213088064)

In [97]:
np.mean(data2, axis=0)

array([ 0.1287498 ,  0.03685672,  0.25807149,  0.39485677, -0.95385154])

In [98]:
np.mean(data2, axis=1)

array([-0.41126264, -0.38742604,  0.71749862])

In [99]:
# minimum은 두개의 행렬을 비교
# min은 한 행렬 안에서의 정리

np.min(data2, axis=1)

array([-0.95100545, -1.28156928, -0.62897991])

In [ ]:
# 표준편차 계산

np.std(data2)

np.float64(0.8270163445403521)

In [101]:
# 분산 계산

np.var(data2)

np.float64(0.6839560341368863)

In [ ]:
# [::-1]하면 뒤집는다는 것 (::가 전체를 의미, -1이 뒤집다)

np.sort(data2)[::-1]

array([[-0.62897991,  0.42011507,  1.05973698,  1.32492625,  1.41169473],
       [-1.28156928, -0.96851708, -0.59535313,  0.38029659,  0.52801272],
       [-0.95100545, -0.66836866, -0.33260748, -0.07813446, -0.02619717]])

In [104]:
# np.sort 정렬 

np.sort(data2, axis=0)

array([[-0.59535313, -0.96851708, -0.02619717, -0.66836866, -1.28156928],
       [-0.07813446, -0.33260748,  0.38029659,  0.52801272, -0.95100545],
       [ 1.05973698,  1.41169473,  0.42011507,  1.32492625, -0.62897991]])

In [ ]:
student1 = [85,90,88,92]
student2 = [78,81,85,86]
student3 = [92,88,91,90]
student4 = [70,75,72,78]
student5 = [88,85,84,89]

scores = np.array([[student1],[student2],[student3],[student4],[student5]])

array([[[85, 90, 88, 92]],

       [[78, 81, 85, 86]],

       [[92, 88, 91, 90]],

       [[70, 75, 72, 78]],

       [[88, 85, 84, 89]]])

In [113]:
# 각 학생의 평균

student1_avg = np.average(student1)
student2_avg = np.average(student2)
student3_avg = np.average(student3)
student4_avg = np.average(student4)
student5_avg = np.average(student5)

print(student1_avg,student2_avg,student3_avg,student4_avg,student5_avg)

88.75 82.5 90.25 73.75 86.5


In [118]:
# 성적이 가장 안정적인 학생을 찾으시오(표준편차가 낮은 학생)

scores_std = np.std(scores, axis = 0)

print(scores_std)

np.min(scores_std)

[[7.78716893 5.34415569 6.4807407  4.89897949]]


np.float64(4.898979485566356)

In [ ]:
# 90점 이상의 과목수가 가장 많은 학생의 점수를 나열하시오

ret = np.array(scores) > 90
print(ret)



[[[False False False  True]]

 [[False False False False]]

 [[ True False  True False]]

 [[False False False False]]

 [[False False False False]]]
